language: java
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
jdk:
- oraclejdk8
before_script:
- chmod +x gradlew
script:
- ./gradlew javadoc
- ./gradlew check
- ./gradlew jacocoTestReport
after_success:
- ./release.sh
env:
  global:
  - secure: pej9CRMLkBcfGeC0w3joanMo89NnWrdGEYy7aBWfp8Ladm6RbtA0B1TQrgeJTP2G5DuLOGvtzzviv2BRCCxIBIyqd/c/ztf2Pee3pCojVj98U3kfl1v4cw9CpB9gNZFGn/+HcqeYKpHFQvOkcJeSlfQSAneNDs18QHf0RYZnK6K7WHNbUbLjWGfCoIiNiGI4Nj23wTLtWqJgAQ/ZuMLQpgFBaiwxGh10fo89qBoVGWman29yE5YUsaFxSp76+9hztKp5rrbXpxyjhaLxF1YbjOl/LZcOuVV+9OLfzkyNIEhdFwcKAn0/t5Ohgwp2PqwA3oIpirYolqXC8Ct0dveAHpg0gF0urmCBN4srnhOmP2LHZu71OHkWaFQpRPZ+5otsUitmq/ksOKgAiRa88fA0xunS4DIPrwvFIlpj9gseqHG+dGW1b7ONSX2JLjLqfb4oQcwebS1WrT6VMWVbPpPj7tifhWohFNGXFiwQZX9Ps3QMjxwZ6f5SjOwfYRc5fCjbcNEZ5mC7v6tm40THg4EYxqCEW3glVLJ4bIjUGE8BA1SyF7ZTdw44ts0xXIeQyVXnhtvO81/MjSq1OBbVZKbX6ItPRzLxLAhlKjvDSgA6o+6qAAbBhvxtwz8rp9dyp3SumNatRMjBlCLnJqd35UYiuTWVhQUdHlrsJ/0fiFdezCE=
  - secure: j2DAZc/N4rot5RgClScWm5rddhRAq6eSmjh1iv34LPfIehiPLrS3OZkpobI2FXZ4uPaRs1FFLuQLtUmV8Mp2rsydOSnBdZH2KbGAh00aSd/S3v51kYgN1kmIgykP+yFM9OnE/lcw1V2Zb4vgRJQaGkoyGvaUs9xLgejlelbij3cqKXhypWIWWyFl64xSyGtLOz7HMW07ZDyW/UgVELo9aQEMwi5ne3B3ImqgAnUnQm3jSc/nrJNiyVoJ4WaWZSoS/xt4cJPQET8tgmaJ5nlrBpD/1csUm8ZSIOhr6M3cw1HKogzPrtMS/Cegr+yerNbTAVxBBZH4X6iSn5oo0E6DTRRSbts7nJDoIUUPXc5lftBbEq3Vv0c85VlzDFnhvap9gh+HF9eHmvtsA04njalw+ENlqVvhCIc/ineBopTVZ+1AXUCsUYvTP5r0uWzw3wqdr/7JUN8Li8QWWv2dMgGAb31b3uX570mg9jt4WENaC1SQWGd/uYEt0O4JnioiUMIe1iwrjCPERaoqE5PcQjj7Tdh4sC2EDDoZSkvczA6MCtBNLHqaYO24jgBq+U78ip2Uqm04Lh5N/d5DsFklMTVQhcAIWf5nQgX405dN6YJ0zoHjp8bGDbIYr+XE+VOwGooJphXSrUHZwN3paVrdM9EWVCaCHeOR6bz3PYG9/xylLnQ=
